[package]
name = "rltest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.raylib]
git = "https://github.com/litten2up/raylib-rs"
branch = "4.6.0"
features = ["wayland"]
